export enum TaskParamType {
  STRING = 'STRING',
  TEXTAREA = 'TEXTAREA',
  PASSWORD = 'PASSWORD',
  NUMBER = 'NUMBER',
  BOOLEAN = 'BOOLEAN',
  DATE = 'DATE',
  TIME = 'TIME',
  DATETIME = 'DATETIME',
}
