export enum TaskType {
  GMAIL_TRIGGER = 'GMAIL_TRIGGER',
  SEND_GMAIL_EMAIL = 'SEND_GMAIL_EMAIL',
  CUSTOM_WEBHOOK = 'CUSTOM_WEBHOOK',
  WEBHOOK_RESPONSE = 'WEBHOOK_RESPONSE',
  GET_VARIABLE_FROM_RESPONSE = 'GET_VARIABLE_FROM_RESPONSE',
  TEXT_INPUT = 'TEXT_INPUT',
  TEXTAREA = 'TEXTAREA',
  AGENT = 'AGENT',
}
