export enum QUERY_KEYS {
  GET_SESSION = 'GET_SESSION',
  GET_ORGANIZATION_MEMBERS = 'GET_ORGANIZATION_MEMBERS',

  // Integrations
  GET_ORGANIZATION_INTEGRATIONS = 'GET_ORGANIZATION_INTEGRATIONS',
  GET_INTEGRATION = 'GET_INTEGRATION',

  // Workflows
  GET_ORGANIZATION_WORKFLOWS = 'GET_ORGANIZATION_WORKFLOWS',
  GET_ORGANIZATION_WORKFLOW_BY_ID = 'GET_ORGANIZATION_WORKFLOW_BY_ID',

  // Workflow Executions
  GET_WORKFLOW_EXECUTION_BY_ID = 'GET_WORKFLOW_EXECUTION_BY_ID',
}
